# Generated by Django 5.0.3 on 2024-04-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('b', 'B'), ('m', 'M'), ('phd', 'PhD')], default='b', max_length=30),
        ),
    ]
