# Generated by Django 5.0.3 on 2024-04-10 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Address nomi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Yoshi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('b', 'B'), ('m', 'M'), ('phd', 'PhD')], default='b', max_length=30, verbose_name='Status'),
        ),
    ]
